 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: source file for the ultrasonic driver
 *
 * Author: Toka Mohamed
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>
#include "common_macros.h"

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
volatile uint8 g_edgeCount = 0;
volatile uint16 g_timeHigh = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description:
 * Initialize the ICU driver as required
 * Setup the ICU call back function
 * Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void)
{
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING}; /*prescaler FCPU/8, detect raising edge as first edge*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	Icu_init(&Icu_Config);
	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,LOGIC_HIGH);
}
/*
 * Description:
 * Send the Trigger pulse to the ultrasonic
*/
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);
}
/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function
 * Start the measurements by the ICU from this moment
 * Return: The measured distance in Centimeter
*/
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance=0;
	Ultrasonic_Trigger(); /*Send the trigger pulse*/
    distance = (uint16)(g_timeHigh*0.017);
    return distance;
}
/*
 * Description:
 * This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
*/
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		Icu_clearTimerValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		Icu_DeInit();
	}
}
